//! Pure functions: `AnswerSet` → config.toml text + shell snippet text.
//! Snapshot-tested; the rest of the wizard is a thin TUI around this.

use std::fmt::Write;

use super::answers::{AnswerSet, Language};

/// Render the answer set as a `config.toml` file. Includes leading comments
/// pointing the user back at the wizard and at `chevron doctor`.
#[must_use]
pub fn to_config_toml(answers: &AnswerSet) -> String {
    let mut out = String::with_capacity(1024);
    writeln!(out, "# chevron config — generated by `chevron configure`").ok();
    writeln!(
        out,
        "# Edit by hand, or re-run `chevron configure` to regenerate."
    )
    .ok();
    if let Some(preset) = answers.source_preset {
        writeln!(out, "# Source preset: {}", preset.name()).ok();
    }
    writeln!(out).ok();

    // [segments] section — only emit if the preset overrides the default order.
    if !answers.segment_order.is_empty() {
        writeln!(out, "[segments]").ok();
        write!(out, "order = [").ok();
        for (i, name) in answers.segment_order.iter().enumerate() {
            if i > 0 {
                out.push_str(", ");
            }
            write!(out, "\"{name}\"").ok();
        }
        writeln!(out, "]").ok();
        writeln!(out).ok();
    }

    // Per-segment enable/disable for the language detectors. We always emit
    // these so the resulting config is explicit and re-editable.
    for lang in Language::all() {
        let enabled = answers.languages.contains(&lang);
        writeln!(out, "[segment.{}]", lang.segment_name()).ok();
        writeln!(out, "enabled = {enabled}").ok();
        writeln!(out).ok();
    }

    // Explicitly-disabled segments not already covered by the languages list.
    for name in &answers.disabled_segments {
        if Language::all().iter().any(|l| l.segment_name() == *name) {
            continue; // already handled above
        }
        writeln!(out, "[segment.{name}]").ok();
        writeln!(out, "enabled = false").ok();
        writeln!(out).ok();
    }

    // Icons preference — stored for future use; renderer does not yet swap.
    writeln!(out, "[icons]").ok();
    writeln!(
        out,
        "# v1: stored only — segment glyphs are not yet swapped based on this."
    )
    .ok();
    writeln!(out, "mode = \"{}\"", answers.icons.config_name()).ok();

    out
}

/// Render the shell-rc snippet the user should paste. The snippet emits only
/// the env vars that differ from chevron's compiled defaults, so a Lean-preset
/// user gets just the `eval` line.
#[must_use]
pub fn to_shell_snippet(answers: &AnswerSet, shell: &str) -> String {
    let mut out = String::with_capacity(256);
    writeln!(
        out,
        "# Add to your shell rc — generated by `chevron configure`"
    )
    .ok();
    let f = &answers.features;
    let defaults = super::answers::Features::default();

    // Each toggle is written only when it deviates from the default. Keeps
    // the snippet short for users who picked the standard choices.
    if f.osc133 != defaults.osc133 {
        write_export(
            &mut out,
            shell,
            "CHEVRON_OSC133",
            if f.osc133 { "1" } else { "0" },
        );
    }
    if f.transient != defaults.transient {
        write_export(
            &mut out,
            shell,
            "CHEVRON_TRANSIENT",
            if f.transient { "1" } else { "0" },
        );
    }
    if f.async_render != defaults.async_render {
        write_export(
            &mut out,
            shell,
            "CHEVRON_ASYNC",
            if f.async_render { "1" } else { "0" },
        );
    }
    if f.history != defaults.history {
        write_export(
            &mut out,
            shell,
            "CHEVRON_HISTORY",
            if f.history { "1" } else { "0" },
        );
    }
    if f.live != defaults.live {
        write_export(
            &mut out,
            shell,
            "CHEVRON_LIVE",
            if f.live { "1" } else { "0" },
        );
    }
    if let Some(v) = f.capture.env_value() {
        write_export(&mut out, shell, "CHEVRON_CAPTURE_HERE", v);
    }

    match shell {
        "fish" => writeln!(out, "chevron init fish | source").ok(),
        _ => writeln!(out, "eval \"$(chevron init {shell})\"").ok(),
    };
    out
}

fn write_export(out: &mut String, shell: &str, var: &str, value: &str) {
    match shell {
        "fish" => writeln!(out, "set -gx {var} {value}").ok(),
        _ => writeln!(out, "export {var}={value}").ok(),
    };
}

#[cfg(test)]
mod tests {
    use super::super::answers::{AnswerSet, CaptureMode, Features, Language, Preset};
    use super::super::presets::from_preset;
    use super::*;

    // ── config.toml output ────────────────────────────────────────────────

    #[test]
    fn lean_emits_minimal_toml() {
        let toml = to_config_toml(&from_preset(Preset::Lean));
        // No [segments] block since lean uses default order.
        assert!(
            !toml.contains("[segments]"),
            "lean should not pin order: {toml}"
        );
        // All three language segments are enabled.
        assert!(toml.contains("[segment.node]"));
        assert!(toml.contains("[segment.python]"));
        assert!(toml.contains("[segment.rust_toolchain]"));
        assert!(toml.matches("enabled = true").count() >= 3);
        // Source-preset comment is present.
        assert!(toml.contains("Source preset: lean"));
    }

    #[test]
    fn pure_emits_segments_order() {
        let toml = to_config_toml(&from_preset(Preset::Pure));
        assert!(toml.contains("[segments]"));
        assert!(toml.contains("order = [\"path\", \"git\", \"character\"]"));
        // Languages disabled.
        assert!(toml.contains("[segment.node]") && toml.contains("enabled = false"));
    }

    #[test]
    fn minimal_emits_ascii_icon_mode() {
        let toml = to_config_toml(&from_preset(Preset::Minimal));
        assert!(toml.contains("[icons]"));
        assert!(toml.contains("mode = \"ascii\""));
    }

    #[test]
    fn rainbow_does_not_pin_order() {
        // Rainbow shows all default segments, so order should be omitted
        // (using chevron's default).
        let toml = to_config_toml(&from_preset(Preset::Rainbow));
        assert!(!toml.contains("[segments]"));
    }

    #[test]
    fn custom_disabled_segment_appears_with_enabled_false() {
        let mut a = from_preset(Preset::Lean);
        a.disabled_segments = vec!["hostname"];
        let toml = to_config_toml(&a);
        assert!(toml.contains("[segment.hostname]"));
        // Find the line and confirm it's set to false.
        let hostname_idx = toml.find("[segment.hostname]").unwrap();
        let after = &toml[hostname_idx..];
        let next_enabled = after.lines().nth(1).unwrap();
        assert_eq!(next_enabled, "enabled = false");
    }

    #[test]
    fn languages_disabled_when_omitted() {
        let mut a = from_preset(Preset::Lean);
        a.languages = vec![Language::Python];
        let toml = to_config_toml(&a);
        // node should be enabled = false, python should be enabled = true.
        let node_idx = toml.find("[segment.node]").unwrap();
        let node_line = toml[node_idx..].lines().nth(1).unwrap();
        assert_eq!(node_line, "enabled = false");
        let py_idx = toml.find("[segment.python]").unwrap();
        let py_line = toml[py_idx..].lines().nth(1).unwrap();
        assert_eq!(py_line, "enabled = true");
    }

    // ── shell snippet output ──────────────────────────────────────────────

    #[test]
    fn lean_snippet_is_just_the_eval_line() {
        let snippet = to_shell_snippet(&from_preset(Preset::Lean), "zsh");
        // Lean uses all defaults, so no exports needed.
        assert!(!snippet.contains("export CHEVRON_"));
        assert!(snippet.contains("eval \"$(chevron init zsh)\""));
    }

    #[test]
    fn fish_uses_set_gx_and_pipe_to_source() {
        let a = AnswerSet {
            features: Features {
                async_render: true,
                ..Features::default()
            },
            ..AnswerSet::default()
        };
        let snippet = to_shell_snippet(&a, "fish");
        assert!(snippet.contains("set -gx CHEVRON_ASYNC 1"));
        assert!(snippet.contains("chevron init fish | source"));
        assert!(!snippet.contains("export "));
    }

    #[test]
    fn bash_uses_export_and_eval() {
        let a = AnswerSet {
            features: Features {
                history: false,
                ..Features::default()
            },
            ..AnswerSet::default()
        };
        let snippet = to_shell_snippet(&a, "bash");
        assert!(snippet.contains("export CHEVRON_HISTORY=0"));
        assert!(snippet.contains("eval \"$(chevron init bash)\""));
    }

    #[test]
    fn each_feature_toggles_only_when_deviating_from_default() {
        let a = AnswerSet {
            features: Features {
                osc133: false,
                transient: false,
                async_render: true,
                history: false,
                live: true,
                capture: CaptureMode::AlwaysOn,
            },
            ..AnswerSet::default()
        };
        let s = to_shell_snippet(&a, "zsh");
        assert!(s.contains("CHEVRON_OSC133=0"));
        assert!(s.contains("CHEVRON_TRANSIENT=0"));
        assert!(s.contains("CHEVRON_ASYNC=1"));
        assert!(s.contains("CHEVRON_HISTORY=0"));
        assert!(s.contains("CHEVRON_LIVE=1"));
        assert!(s.contains("CHEVRON_CAPTURE_HERE=1"));
    }

    #[test]
    fn capture_per_cwd_uses_string_value() {
        let a = AnswerSet {
            features: Features {
                capture: CaptureMode::PerCwd,
                ..Features::default()
            },
            ..AnswerSet::default()
        };
        let s = to_shell_snippet(&a, "zsh");
        assert!(s.contains("CHEVRON_CAPTURE_HERE=per_cwd"));
    }

    #[test]
    fn capture_off_omits_the_var_entirely() {
        let a = AnswerSet::default(); // capture defaults to Off
        let s = to_shell_snippet(&a, "zsh");
        assert!(!s.contains("CHEVRON_CAPTURE_HERE"));
    }

    // ── round-trip: emitted TOML parses back into a valid Config ──────────

    #[test]
    fn lean_emitted_toml_parses_as_config() {
        let toml = to_config_toml(&from_preset(Preset::Lean));
        let cfg: Result<crate::config::Config, _> = toml::from_str(&toml);
        assert!(cfg.is_ok(), "lean TOML must parse: {toml}\n\n{cfg:?}");
    }

    #[test]
    fn pure_emitted_toml_parses_and_has_expected_order() {
        let toml = to_config_toml(&from_preset(Preset::Pure));
        let cfg: crate::config::Config = toml::from_str(&toml).expect("pure TOML must parse");
        assert_eq!(cfg.segments.order, vec!["path", "git", "character"]);
        assert!(!cfg.segment_enabled("node"), "pure disables node");
        assert!(cfg.segment_enabled("git"), "pure keeps git");
    }

    #[test]
    fn every_preset_round_trips_through_toml() {
        for preset in Preset::all() {
            let toml = to_config_toml(&from_preset(preset));
            let parsed: Result<crate::config::Config, _> = toml::from_str(&toml);
            assert!(parsed.is_ok(), "{preset:?} TOML failed to parse: {toml}");
        }
    }
}
