//! Pure functions: `AnswerSet` → config.toml text + shell snippet text.
//! Snapshot-tested; the rest of the wizard is a thin TUI around this.

use std::fmt::Write;

use super::answers::{AnswerSet, Language};

/// Render the answer set as a `config.toml` file. Includes leading comments
/// pointing the user back at the wizard and at `chevron doctor`.
#[must_use]
pub fn to_config_toml(answers: &AnswerSet) -> String {
    let mut out = String::with_capacity(1024);
    writeln!(out, "# chevron config — generated by `chevron configure`").ok();
    writeln!(
        out,
        "# Edit by hand, or re-run `chevron configure` to regenerate."
    )
    .ok();
    if let Some(preset) = answers.source_preset {
        writeln!(out, "# Source preset: {}", preset.name()).ok();
    }
    writeln!(out).ok();

    // [segments] section — only emit if the preset overrides the default order.
    if !answers.segment_order.is_empty() {
        writeln!(out, "[segments]").ok();
        write!(out, "order = [").ok();
        for (i, name) in answers.segment_order.iter().enumerate() {
            if i > 0 {
                out.push_str(", ");
            }
            write!(out, "\"{name}\"").ok();
        }
        writeln!(out, "]").ok();
        writeln!(out).ok();
    }

    // Per-segment enable/disable for the language detectors. We always emit
    // these so the resulting config is explicit and re-editable.
    for lang in Language::all() {
        let enabled = answers.languages.contains(&lang);
        writeln!(out, "[segment.{}]", lang.segment_name()).ok();
        writeln!(out, "enabled = {enabled}").ok();
        writeln!(out).ok();
    }

    // Explicitly-disabled segments not already covered by the languages list.
    for name in &answers.disabled_segments {
        if Language::all().iter().any(|l| l.segment_name() == *name) {
            continue; // already handled above
        }
        writeln!(out, "[segment.{name}]").ok();
        writeln!(out, "enabled = false").ok();
        writeln!(out).ok();
    }

    // Icons preference — stored for future use; renderer does not yet swap.
    writeln!(out, "[icons]").ok();
    writeln!(
        out,
        "# v1: stored only — segment glyphs are not yet swapped based on this."
    )
    .ok();
    writeln!(out, "mode = \"{}\"", answers.icons.config_name()).ok();
    writeln!(out).ok();

    // [shell] block — `chevron init <shell>` reads these and emits an
    // env-var preamble. Env vars set before sourcing still win.
    let f = &answers.features;
    writeln!(out, "[shell]").ok();
    writeln!(out, "osc133 = {}", f.osc133).ok();
    writeln!(out, "transient = {}", f.transient).ok();
    writeln!(out, "async_render = {}", f.async_render).ok();
    writeln!(out, "history = {}", f.history).ok();
    writeln!(out, "live = {}", f.live).ok();

    out
}

/// Render the shell-rc snippet the user should paste. After the config-driven
/// init refactor, this is a single `eval` line — all toggles live in
/// config.toml's `[shell]` block. The only exception is output capture
/// (`CHEVRON_CAPTURE_HERE`), which is still env-only.
#[must_use]
pub fn to_shell_snippet(answers: &AnswerSet, shell: &str) -> String {
    let mut out = String::with_capacity(128);
    writeln!(
        out,
        "# Add to your shell rc — generated by `chevron configure`"
    )
    .ok();

    if let Some(v) = answers.features.capture.env_value() {
        match shell {
            "fish" => writeln!(out, "set -gx CHEVRON_CAPTURE_HERE {v}").ok(),
            _ => writeln!(out, "export CHEVRON_CAPTURE_HERE={v}").ok(),
        };
    }

    match shell {
        "fish" => writeln!(out, "chevron init fish | source").ok(),
        _ => writeln!(out, "eval \"$(chevron init {shell})\"").ok(),
    };
    out
}

#[cfg(test)]
mod tests {
    use super::super::answers::{AnswerSet, CaptureMode, Features, Language, Preset};
    use super::super::presets::from_preset;
    use super::*;

    // ── config.toml output ────────────────────────────────────────────────

    #[test]
    fn lean_emits_minimal_toml() {
        let toml = to_config_toml(&from_preset(Preset::Lean));
        assert!(
            !toml.contains("[segments]"),
            "lean should not pin order: {toml}"
        );
        assert!(toml.contains("[segment.node]"));
        assert!(toml.contains("[segment.python]"));
        assert!(toml.contains("[segment.rust_toolchain]"));
        assert!(toml.matches("enabled = true").count() >= 3);
        assert!(toml.contains("Source preset: lean"));
    }

    #[test]
    fn pure_emits_segments_order() {
        let toml = to_config_toml(&from_preset(Preset::Pure));
        assert!(toml.contains("[segments]"));
        assert!(toml.contains("order = [\"path\", \"git\", \"character\"]"));
        assert!(toml.contains("[segment.node]") && toml.contains("enabled = false"));
    }

    #[test]
    fn minimal_emits_ascii_icon_mode() {
        let toml = to_config_toml(&from_preset(Preset::Minimal));
        assert!(toml.contains("[icons]"));
        assert!(toml.contains("mode = \"ascii\""));
    }

    #[test]
    fn rainbow_does_not_pin_order() {
        let toml = to_config_toml(&from_preset(Preset::Rainbow));
        assert!(!toml.contains("[segments]"));
    }

    #[test]
    fn custom_disabled_segment_appears_with_enabled_false() {
        let mut a = from_preset(Preset::Lean);
        a.disabled_segments = vec!["hostname"];
        let toml = to_config_toml(&a);
        assert!(toml.contains("[segment.hostname]"));
        let hostname_idx = toml.find("[segment.hostname]").unwrap();
        let after = &toml[hostname_idx..];
        let next_enabled = after.lines().nth(1).unwrap();
        assert_eq!(next_enabled, "enabled = false");
    }

    #[test]
    fn languages_disabled_when_omitted() {
        let mut a = from_preset(Preset::Lean);
        a.languages = vec![Language::Python];
        let toml = to_config_toml(&a);
        let node_idx = toml.find("[segment.node]").unwrap();
        let node_line = toml[node_idx..].lines().nth(1).unwrap();
        assert_eq!(node_line, "enabled = false");
        let py_idx = toml.find("[segment.python]").unwrap();
        let py_line = toml[py_idx..].lines().nth(1).unwrap();
        assert_eq!(py_line, "enabled = true");
    }

    // ── [shell] block ─────────────────────────────────────────────────────

    #[test]
    fn lean_emits_shell_block_with_defaults() {
        let toml = to_config_toml(&from_preset(Preset::Lean));
        assert!(toml.contains("[shell]"));
        assert!(toml.contains("osc133 = true"));
        assert!(toml.contains("transient = true"));
        assert!(toml.contains("async_render = false"));
        assert!(toml.contains("history = true"));
        assert!(toml.contains("live = false"));
    }

    #[test]
    fn minimal_emits_shell_block_with_overrides() {
        // Minimal preset disables OSC 133 and transient.
        let toml = to_config_toml(&from_preset(Preset::Minimal));
        assert!(toml.contains("osc133 = false"));
        assert!(toml.contains("transient = false"));
    }

    // ── shell snippet output ──────────────────────────────────────────────

    #[test]
    fn lean_snippet_is_just_the_eval_line() {
        let snippet = to_shell_snippet(&from_preset(Preset::Lean), "zsh");
        assert!(
            !snippet.contains("export CHEVRON_"),
            "snippet should not export any CHEVRON_* vars: {snippet}"
        );
        assert!(snippet.contains("eval \"$(chevron init zsh)\""));
    }

    #[test]
    fn even_minimal_snippet_collapses_to_eval_only() {
        // After the config-driven refactor, even non-default features
        // live in [shell] — so the snippet is one eval line.
        let snippet = to_shell_snippet(&from_preset(Preset::Minimal), "zsh");
        assert!(!snippet.contains("export CHEVRON_OSC"));
        assert!(!snippet.contains("export CHEVRON_TRANSIENT"));
        assert!(snippet.contains("eval \"$(chevron init zsh)\""));
    }

    #[test]
    fn fish_uses_pipe_to_source() {
        let snippet = to_shell_snippet(&from_preset(Preset::Lean), "fish");
        assert!(snippet.contains("chevron init fish | source"));
        assert!(!snippet.contains("export "));
    }

    #[test]
    fn bash_uses_eval() {
        let snippet = to_shell_snippet(&from_preset(Preset::Lean), "bash");
        assert!(snippet.contains("eval \"$(chevron init bash)\""));
    }

    #[test]
    fn capture_per_cwd_stays_in_snippet_as_env() {
        // Capture mode isn't part of [shell] — still emitted in the snippet.
        let a = AnswerSet {
            features: Features {
                capture: CaptureMode::PerCwd,
                ..Features::default()
            },
            ..AnswerSet::default()
        };
        let s = to_shell_snippet(&a, "zsh");
        assert!(s.contains("CHEVRON_CAPTURE_HERE=per_cwd"));
    }

    #[test]
    fn capture_always_on_in_snippet() {
        let a = AnswerSet {
            features: Features {
                capture: CaptureMode::AlwaysOn,
                ..Features::default()
            },
            ..AnswerSet::default()
        };
        let s = to_shell_snippet(&a, "zsh");
        assert!(s.contains("CHEVRON_CAPTURE_HERE=1"));
    }

    #[test]
    fn capture_off_omits_the_var_entirely() {
        let a = AnswerSet::default();
        let s = to_shell_snippet(&a, "zsh");
        assert!(!s.contains("CHEVRON_CAPTURE_HERE"));
    }

    // ── round-trip: emitted TOML parses back into a valid Config ──────────

    #[test]
    fn lean_emitted_toml_parses_as_config() {
        let toml = to_config_toml(&from_preset(Preset::Lean));
        let cfg: Result<crate::config::Config, _> = toml::from_str(&toml);
        assert!(cfg.is_ok(), "lean TOML must parse: {toml}\n\n{cfg:?}");
    }

    #[test]
    fn pure_emitted_toml_parses_and_has_expected_order() {
        let toml = to_config_toml(&from_preset(Preset::Pure));
        let cfg: crate::config::Config = toml::from_str(&toml).expect("pure TOML must parse");
        assert_eq!(cfg.segments.order, vec!["path", "git", "character"]);
        assert!(!cfg.segment_enabled("node"), "pure disables node");
        assert!(cfg.segment_enabled("git"), "pure keeps git");
    }

    #[test]
    fn every_preset_round_trips_through_toml() {
        for preset in Preset::all() {
            let toml = to_config_toml(&from_preset(preset));
            let parsed: Result<crate::config::Config, _> = toml::from_str(&toml);
            assert!(parsed.is_ok(), "{preset:?} TOML failed to parse: {toml}");
        }
    }

    #[test]
    fn lean_toml_shell_block_round_trips_to_default_shellconfig() {
        let toml = to_config_toml(&from_preset(Preset::Lean));
        let cfg: crate::config::Config = toml::from_str(&toml).unwrap();
        // Lean uses Features::default() which matches ShellConfig defaults.
        assert!(cfg.shell.osc133);
        assert!(cfg.shell.transient);
        assert!(!cfg.shell.async_render);
        assert!(cfg.shell.history);
        assert!(!cfg.shell.live);
    }
}
